# Generated by Django 5.1.3 on 2025-03-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('title', models.CharField(default='Blog', max_length=100)),
                ('content', models.TextField(max_length=10000)),
                ('date', models.DateField()),
                ('ananymous', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('dob', models.DateField(default='2000-01-01')),
                ('role', models.CharField(default='Set your role', max_length=100)),
                ('about', models.TextField(default='Tell me about yourself...', max_length=1000)),
                ('badges', models.JSONField(default=list)),
                ('saved', models.JSONField(default=list)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
