# Generated by Django 5.1.3 on 2024-12-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='me',
        ),
    ]
