# Generated by Django 5.1.3 on 2025-03-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogs_blockcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
