# Generated by Django 5.1.3 on 2025-03-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogs_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='reported',
            field=models.IntegerField(default=0),
        ),
    ]
