# Generated by Django 5.1.3 on 2025-01-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogs_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='likes',
        ),
    ]
