# Generated by Django 5.1.3 on 2025-02-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blogs_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='likes',
            name='blog_id',
            field=models.IntegerField(),
        ),
    ]
