# Generated by Django 5.1.3 on 2025-02-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comments_alter_likes_blog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='likes',
        ),
    ]
