# Generated by Django 5.1.3 on 2025-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_blogs_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
