# Generated by Django 5.1.3 on 2025-02-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_blogs_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=1000)),
                ('expertise', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(default='Blog', max_length=100),
        ),
    ]
