# Generated by Django 5.1.3 on 2025-02-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userdetails_alter_blogs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='saved',
            field=models.TextField(default=list),
        ),
    ]
