# Generated by Django 5.1.3 on 2025-02-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userdetails_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=1000)),
                ('expertise', models.JSONField(default=list)),
                ('saved', models.TextField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='Userdetails',
        ),
    ]
